version: "3.8"
services:
  mongodb: 
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
    #    MONGO_INITDB_ROOT_USERNAME: ilona
    #    MONGO_INITDB_ROOT_PASSWORD: secret
    #   # - MONGO_INITDB_ROOT_USERNAME=ilona
    env_file:
      - ./env/mongo.env
  backend:
    build: ./backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile-custom-name
    #   args:
    #     some-arg: 1
    ports: 
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
        - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs: